Repository sourmash-bio/sourmash, pull requests merged in 2020-01, with the labels that each got.

#824 [MRG] set up publishing workflow for NPM and crates.io
  .github/workflows/rust.yml
  setup.py
  src/core/Cargo.toml
Labels: rust

#826 Do add_many in Rust, use it in LCA _signatures
  include/sourmash.h
  sourmash/_minhash.py
  sourmash/lca/lca_utils.py
  src/core/src/ffi/minhash.rs
Labels: ready for merge!, rust

#785 Implement improved & consistent argument parsing
  sourmash/__init__.py
  sourmash/__main__.py
  sourmash/cli/.gitignore
  sourmash/cli/__init__.py
  sourmash/cli/categorize.py
  sourmash/cli/compare.py
  sourmash/cli/compute.py
  sourmash/cli/dump.py
  sourmash/cli/gather.py
  sourmash/cli/import_csv.py
  sourmash/cli/index.py
  sourmash/cli/info.py
  sourmash/cli/lca/__init__.py
  sourmash/cli/lca/classify.py
  sourmash/cli/lca/compare_csv.py
  sourmash/cli/lca/gather.py
  sourmash/cli/lca/index.py
  sourmash/cli/lca/rankinfo.py
  sourmash/cli/lca/summarize.py
  sourmash/cli/migrate.py
  sourmash/cli/multigather.py
  sourmash/cli/plot.py
  sourmash/cli/sbt_combine.py
  sourmash/cli/search.py
  sourmash/cli/sig/__init__.py
  sourmash/cli/sig/describe.py
  sourmash/cli/sig/downsample.py
  sourmash/cli/sig/export.py
  sourmash/cli/sig/extract.py
  sourmash/cli/sig/filter.py
  sourmash/cli/sig/flatten.py
  sourmash/cli/sig/ingest.py
  sourmash/cli/sig/intersect.py
  sourmash/cli/sig/merge.py
  sourmash/cli/sig/overlap.py
  sourmash/cli/sig/rename.py
  sourmash/cli/sig/subtract.py
  sourmash/cli/storage/__init__.py
  sourmash/cli/storage/convert.py
  sourmash/cli/utils.py
  sourmash/cli/watch.py
  sourmash/command_compute.py
  sourmash/commands.py
  sourmash/lca/__main__.py
  sourmash/lca/command_classify.py
  sourmash/lca/command_compare_csv.py
  sourmash/lca/command_gather.py
  sourmash/lca/command_index.py
  sourmash/lca/command_rankinfo.py
  sourmash/lca/command_summarize.py
  sourmash/sbt.py
  sourmash/sig/__main__.py
  sourmash/sourmash_args.py
  tests/test_sourmash.py
Labels: ready for merge!

#839 Trigger new Software Heritage archival snapshot on new tags
  .github/workflows/metadata.yml
Labels: ready for merge!

#532 Moving loading and save sigs to Rust
  include/sourmash.h
  setup.py
  sourmash/cli/sig/describe.py
  sourmash/commands.py
  sourmash/sig/__main__.py
  sourmash/signature.py
  sourmash/signature_json.py
  sourmash/sourmash_args.py
  src/core/src/ffi/minhash.rs
  src/core/src/sketch/minhash.rs
  tests/test__minhash.py
  tests/test_signature.py
  tests/test_signature_json.py
  tests/test_sourmash.py
Labels: ready for merge!, rust

#784 Expose an unload method for SBT nodes
  sourmash/commands.py
  sourmash/sbt.py
  sourmash/sbtmh.py
  sourmash/search.py
Labels: ready for merge!

#840 Keep smaller temp lists in _signatures
  benchmarks/benchmarks.py
  sourmash/lca/lca_utils.py
  src/core/src/ffi/minhash.rs
Labels: ready for merge!

#846 Ignore .sig and .sbt files for repo language stats
  .gitattributes
Labels: doc, enhancement, idea, ready for merge!, sbt

#852 Only run Rust checks if it changes Rust code
  .github/workflows/rust.yml
Labels: ready for merge!

#854 add --labeltext to plot
  sourmash/cli/plot.py
  sourmash/commands.py
  tests/test_sourmash.py
Labels: ready for merge!

#845 Compute oxidation
  Makefile
  benchmarks/benchmarks.py
  include/sourmash.h
  setup.py
  sourmash/_minhash.py
  sourmash/cli/compute.py
  sourmash/command_compute.py
  sourmash/exceptions.py
  sourmash/signature.py
  src/core/Cargo.toml
  src/core/benches/compute.rs
  src/core/src/cmd.rs
  src/core/src/errors.rs
  src/core/src/ffi/cmd/compute.rs
  src/core/src/ffi/cmd/mod.rs
  src/core/src/ffi/minhash.rs
  src/core/src/ffi/mod.rs
  src/core/src/ffi/signature.rs
  src/core/src/signature.rs
  src/core/src/sketch/minhash.rs
  src/core/src/sketch/ukhs.rs
  src/core/src/wasm.rs
  src/core/tests/minhash.rs
  src/core/tests/signature.rs
  tests/test_sourmash_compute.py
Labels: ready for merge!

#856 Refactor and oxidize downsampling code in sbtmh.py
  include/sourmash.h
  sourmash/_minhash.py
  sourmash/commands.py
  sourmash/compare.py
  sourmash/sbt.py
  sourmash/sbtmh.py
  sourmash/signature.py
  src/core/Cargo.toml
  src/core/src/errors.rs
  src/core/src/ffi/minhash.rs
  src/core/src/index/mod.rs
  src/core/src/sketch/minhash.rs
  src/core/tests/minhash.rs
  tests/test__minhash.py
  tests/test_signature.py
  tests/test_sourmash.py
Labels: ready for merge!
